use rand::seq::SliceRandom;
use rand::{Rng, rngs::OsRng};

const ADJECTIVES: &[&str] = &[
    "ancient",
    "bold",
    "brave",
    "breezy",
    "bright",
    "calm",
    "cheerful",
    "clever",
    "cosmic",
    "crimson",
    "curious",
    "daring",
    "dashing",
    "dizzy",
    "eager",
    "electric",
    "fearless",
    "feral",
    "fierce",
    "fluffy",
    "giddy",
    "glimmering",
    "golden",
    "grumpy",
    "happy",
    "humble",
    "jazzy",
    "jolly",
    "lively",
    "lucky",
    "mellow",
    "merry",
    "mighty",
    "misty",
    "nimble",
    "noisy",
    "peppy",
    "plucky",
    "polite",
    "quiet",
    "quirky",
    "rapid",
    "rowdy",
    "salty",
    "sassy",
    "savvy",
    "scruffy",
    "silver",
    "sleepy",
    "sly",
    "smoky",
    "snappy",
    "sneaky",
    "spicy",
    "sunny",
    "swift",
    "thunder",
    "tiny",
    "turbo",
    "velvet",
    "vivid",
    "wandering",
    "wild",
    "witty",
    "zesty",
];

const ANIMALS: &[&str] = &[
    "axolotl",
    "badger",
    "bison",
    "capybara",
    "cheetah",
    "chinchilla",
    "cobra",
    "coyote",
    "cuttlefish",
    "dolphin",
    "eagle",
    "falcon",
    "ferret",
    "flamingo",
    "fox",
    "gecko",
    "gibbon",
    "giraffe",
    "gopher",
    "gorilla",
    "hedgehog",
    "heron",
    "hippo",
    "iguana",
    "jaguar",
    "jellyfish",
    "kangaroo",
    "kestrel",
    "kingfisher",
    "koala",
    "koi",
    "lemur",
    "leopard",
    "llama",
    "lobster",
    "lynx",
    "manatee",
    "mantis",
    "marmot",
    "meerkat",
    "mongoose",
    "moose",
    "narwhal",
    "newt",
    "ocelot",
    "octopus",
    "orca",
    "osprey",
    "otter",
    "owl",
    "panda",
    "pangolin",
    "panther",
    "penguin",
    "platypus",
    "puffin",
    "raccoon",
    "raven",
    "rhino",
    "salamander",
    "seal",
    "shark",
    "sloth",
    "stingray",
    "tapir",
    "tiger",
    "toucan",
    "turtle",
    "viper",
    "walrus",
    "weasel",
    "whale",
    "wolf",
    "wombat",
    "yak",
];

pub fn name() -> String {
    let mut rng = OsRng;
    let adj = ADJECTIVES.choose(&mut rng).copied().unwrap_or("spry");
    let animal = ANIMALS.choose(&mut rng).copied().unwrap_or("otter");
    format!("{adj}-{animal}")
}

pub fn id() -> String {
    let mut rng = OsRng;
    let a: u64 = rng.r#gen();
    let b: u32 = rng.r#gen();
    format!("cli-{a:016x}{b:08x}")
}
